# Generated by Django 3.1.7 on 2021-03-29 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='added_data',
            new_name='added_date',
        ),
    ]
